package repository

import (
	"context"
	"log"
	"time"

	"github.com/leal/pkg/campaigns/domain"
)

func (r *CampaignRepository) Create(ctx context.Context, name, description string, branchOffice int) (*domain.Campaign, error) {
	log.Println("creating a new Campaign")
	res, err := r.Db.Exec(`insert into lealtest.campañas (nombre, fecha_activacion, fecha_inactivacion, estado, sucursal, descripcion, createdAt, UpdatedAt) 
		values (?,?,?,?,?,?)`,
		name, time.Time{}, time.Time{}, false, branchOffice, description, time.Now(), time.Time{},
	)
	if err != nil {
		log.Printf("cannot create the campaign: %s", err.Error())
		return nil, err
	}

	id, err := res.LastInsertId()
	if err != nil {
		log.Printf("cannot get the last id autogenerated: %s", err.Error())
		return nil, err
	}

	return &domain.Campaign{
		Id:           int(id),
		Name:         name,
		ActiveDate:   time.Time{},
		InactiveDate: time.Time{},
		State:        false,
		BranchOffice: branchOffice,
		Description:  description,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Time{},
	}, nil
}
