package repository

import (
	"context"
	"log"
	"time"

	"github.com/leal/pkg/campaigns/domain"
)

func (r *Repository) Create(ctx context.Context, name, description string, branchOffice int) (*domain.Campaign, error) {
	log.Println("creating a new Campaign")

	res, err := r.db.Exec(createQuery,
		name, nil, nil, false, branchOffice, description, time.Now(), nil,
	)
	if err != nil {
		log.Printf("cannot create the campaign: %s", err.Error())
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		log.Printf("cannot get the last id autogenerated: %s", err.Error())
		return nil, err
	}

	return &domain.Campaign{
		Id:           int(id),
		Name:         name,
		ActiveDate:   time.Time{},
		InactiveDate: time.Time{},
		State:        false,
		BranchOffice: branchOffice,
		Description:  description,
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Time{},
	}, nil
}
